---
title: "Causal Impact para muertes por distintntas causas"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r}
library(CausalImpact)
library(feather)
library(ggplot2)
```


```{r}

df = read_feather("../datos/input_causal_impact.feather")
causas = unique(df$causa)

results_list <- list()
file_count = 1

pre.period <- c(1, 219)
post.period <- c(220, 231)

for (causa in causas){
    print(causa)
    df_causa = df[df$causa==causa, ]
    y = df_causa$y
    x0 = df_causa$x0 
    data <- cbind(y, x0)
    impact <- CausalImpact(data, pre.period, post.period, alpha=0.05)
    impact.plot <- plot(impact)
    impact.plot <- impact.plot + theme_bw(base_size = 10) +
                 ggtitle(paste("Impacto de Covid para", causa, sep=" "))
    print(impact.plot)
    results = data.frame(impact[[1]])
    results$causa = causa
    results_list[[file_count]] <- results
  
    
    file_count <- file_count + 1
}
all_results = do.call(rbind, results_list) #concatenate list of dataframes
write_feather(all_results,'../datos/results_causal_impact.feather')
```
